[package]
name = "genesis-for-dummies"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"                      
serde = { version = "1.0", features = ["derive"] } 
serde_yaml = "0.9"
serde_json = "1.0"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "0.7.13"